name: Busted

on: [ push, pull_request ]

jobs:

  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.4", "5.3", "5.2" ] # , "luajit-openresty"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup dependencies
        run: |
          luarocks install --deps-only luabehave-scm-1.rockspec
          luarocks install busted
          luarocks install lanes # required for parallel execution
          luarocks install luautf8 # required for decoder unit test
          luarocks install luasocket # required for profiler unit test
          luarocks install luacov
          luarocks install luacov-coveralls

      - name: Run regression tests
        run: busted -c -v

      - name: Check test coverage
        if: success()
        run: |
            luacov src/luabehave
            awk 'BEGIN{ b=0; p=0;} match($0,/^[=]+$/){ b=1;next;} match($0,/^Summary$/){if (b){p=1;}} /.*/ { if  (p) { print $0;} else {b=0;}}' < luacov.report.out | \
            awk  'match($0, /Total.+[0-9]+\s+([0-9\.]+)%$/,a){t=a[1]} {print $0} END{ if (t<=95) {print "\n{ERROR} Low tests coverage (less than 95%) ; current=" t "%"; exit 1}};'; echo $?

      - name: Report test coverage
        if: success()
        continue-on-error: true
        run: luacov-coveralls -i src/luabehave -e .luarocks
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
