name: LuaBehave

on: [ push, pull_request ]

jobs:

  luabehave:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.4", "5.3", "5.2" ]
        penlightVersion: [ "1.13.1", "1.9.2", "1.8.0", "1.6.0", "1.3.2" ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ‘lua’
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Setup ‘luarocks’
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup dependencies
        run: |
          luarocks install penlight ${{ matrix.penlightVersion }}
          luarocks install luassert
          luarocks install argparse
          luarocks install --deps-only luabehave-scm-1.rockspec

      - name: Build ‘luabehave’ (bootstrap)
        run: |
          luarocks make

      - name: Run ‘luabehave’ (dogfood)
        # disable project-local path prefixes to force use of system installation
        run: luabehave
